export const CADASTRO_CREATE = 'CADASTRO_CREATE';
export const SEARCH_RESULT = 'SEARCH_RESULT';
export const SEARCH_RESULT_CLIENTE = 'SEARCH_RESULT_CLIENTE';
export const SEARCH_RESULT_EQUIPAMENTO = 'SEARCH_RESULT_EQUIPAMENTO';
export const SEARCH_RESULT_GRUPO = 'SEARCH_RESULT_GRUPO';

export const ADD_ALERT = 'ADD_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const ADD_EQUIPAMENTO = 'ADD_EQUIPAMENTO';
export const REMOVE_EQUIPAMENTO = 'REMOVE_EQUIPAMENTO';

export const ADD_CLIENTE = 'ADD_CLIENTE';
export const SERVICE_CLIENTE = 'SERVICE_CLIENTE';
export const REMOVE_CLIENTE = 'REMOVE_CLIENTE';

export const ADD_GRUPO = 'ADD_GRUPO';
export const REMOVE_GRUPO = 'REMOVE_GRUPO';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGOUT_USER = 'LOGOUT_USER';


export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';